name = "fftmpi"
version = "0.1.0"

[build]
auto-tests = true
module-naming = false
external-modules = ["mpi", "fftw3"]

[preprocess]
[preprocess.cpp]
macros = ["FFT_FFTW3"]

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
